version: '3.7'

services:
  thriveplanningdb:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Password1
      MYSQL_DATABASE: ThrivePlan
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 60s
      interval: 10s
      retries: 5
    volumes:
      - /opt/ThrivePlanningAPI_data:/var/lib/mysql
 
  thriveplanningapi:
    container_name: thrive-planning-api
    build:
      context: .
    depends_on:
      thriveplanningdb:
        condition: service_healthy
    ports:
      - '80:80'
    links:
      - thriveplanningdb
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-west-2
      - AWS_PROFILE
      - ASPNETCORE_ENVIRONMENT=Local
    volumes:
      # mount credentials files inside the container as read-only
      - ~/.aws/credentials:/root/.aws/credentials:ro
      - ~/.aws/config:/root/.aws/config:ro
